// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908181854_AddCharacterImageUrl")]
    partial class AddCharacterImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FirstAPI.models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("PathId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElementId = 1,
                            Name = "Phainon",
                            PathId = 1,
                            PlanetId = 1,
                            Rating = 100
                        },
                        new
                        {
                            Id = 2,
                            ElementId = 7,
                            Name = "Sunday",
                            PathId = 4,
                            PlanetId = 2,
                            Rating = 8
                        },
                        new
                        {
                            Id = 3,
                            ElementId = 2,
                            Name = "Sparxie",
                            PathId = 8,
                            PlanetId = 3,
                            Rating = 1
                        },
                        new
                        {
                            Id = 4,
                            ElementId = 2,
                            Name = "Fugue",
                            PathId = 5,
                            PlanetId = 4,
                            Rating = 7
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lightning"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wind"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quantum"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Imaginary"
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Lightcone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PathId");

                    b.ToTable("Lightcones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAtk = 687,
                            Name = "Thus Burns The Dawn",
                            PathId = 1,
                            Rarity = 5
                        },
                        new
                        {
                            Id = 2,
                            BaseAtk = 476,
                            Name = "A Grounded Ascent",
                            PathId = 4,
                            Rarity = 5
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Path", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Destruction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Erudition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Harmony"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nihility"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Preservation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abundance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rememberance"
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eternal Land",
                            Name = "Amphoreus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Planet of Festivities",
                            Name = "Penacony"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vibrant Dreamscape",
                            Name = "Planarcadia"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Alliance Flagship",
                            Name = "Xianzhou"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Frozen Leadership",
                            Name = "Belobog"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Geniuses Greetings",
                            Name = "Herta Space Station"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Path of Trailblazing",
                            Name = "Astral Express"
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Character", b =>
                {
                    b.HasOne("FirstAPI.models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAPI.models.Path", "Path")
                        .WithMany()
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAPI.models.Planet", "Planet")
                        .WithMany("Characters")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Path");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("FirstAPI.models.Lightcone", b =>
                {
                    b.HasOne("FirstAPI.models.Path", "Path")
                        .WithMany()
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Path");
                });

            modelBuilder.Entity("FirstAPI.models.Planet", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
