// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FirstAPI.models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phainon",
                            PlanetId = 1,
                            Rating = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sunday",
                            PlanetId = 2,
                            Rating = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sparxie",
                            PlanetId = 3,
                            Rating = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fugue",
                            PlanetId = 4,
                            Rating = 7
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eternal Land",
                            Name = "Amphoreus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Planet of Festivities",
                            Name = "Penacony"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vibrant Dreamscape",
                            Name = "Planarcadia"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Alliance Flagship",
                            Name = "Xianzhou"
                        });
                });

            modelBuilder.Entity("FirstAPI.models.Character", b =>
                {
                    b.HasOne("FirstAPI.models.Planet", "Planet")
                        .WithMany("Characters")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("FirstAPI.models.Planet", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
