// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FirstAPI.models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phainon",
                            Planet = "Amphoreus",
                            Rating = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sunday",
                            Planet = "Penacony",
                            Rating = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sparxie",
                            Planet = "Planarcadia",
                            Rating = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fugue",
                            Planet = "Xianzhou",
                            Rating = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
