@rootURL = http://localhost:5095

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/character
Accept: application/json

###

GET {{rootURL}}/api/character/1
Accept: application/json

###

POST {{rootURL}}/api/character
Content-Type: application/json

{
    "Id" : 5,
    "Name" : "Mydei",
    "PlanetId" : "1",
    "Rating" : 9
}

###

PUT {{rootURL}}/api/character/1
Content-Type: application/json

{
    "Id" : 1,
    "Name" : "Phainon",
    "PlanetId" : 1,
    "Rating" : 10000000 
}

###

DELETE {{rootURL}}/api/character/5

###

GET {{rootURL}}/api/character/1/details
Accept: application/json

###

GET {{rootURL}}/api/character/planets
Accept: application/json